### ISSUE TITLE
Review error handling in createHttpJoseApolloLink module

### ISSUE THREAD

**Issue by MrTibbles** [jaakmusic/jaak.js#24]
Look to amend to the error response handling within the `createHttpJoseApolloLink` module:
```
.then(response =>
  response.text().then(bodyText => {
    try {
      return JSON.parse(bodyText)
    } catch (err) {
      return Promise.reject(err)
    }
  })
)
```
@lmars 
> Could this be replaced with return response.json()?

**Comment by lmars** [comment]
The Apollo related code has now [been removed](https://github.com/jaakmusic/jaak.js/pull/63).
