### ISSUE TITLE
Review the usage of observer.next within createHttpJoseApolloLink module

### ISSUE THREAD

**Issue by MrTibbles** [jaakmusic/jaak.js#25]
@lmars 
> Should this return straight after, or is the intention to call both observer.next and observer.error?

```
.catch(err => {
  if (err.result && err.result.errors && err.result.data) {
    observer.next(err.result)
  }

  observer.error(err)
})
```

**Comment by lmars** [comment]
The Apollo related code has now [been removed](https://github.com/jaakmusic/jaak.js/pull/63).
