### ISSUE TITLE
try/catch tests should force a failure

### ISSUE THREAD

**Issue by malimccalla** [jaakmusic/jaak.js#46]
There are certain tests in our suite that can pass even if they should fail. Take the following test that checks that an invalid account throws an error

```js
try {
  generateAccessVoucher(licenseID, account, nonce)
} catch (error) {
  expect(error).toBeDefined()
}
```

If a correct account is passed in then the test will pass for the wrong reason. One way to prevent this is to force fail the test if it does not throw

```js
try {
  generateAccessVoucher(licenseID, account, nonce)
  // If execution gets this far then something unexpected happened so we should fail the test
  expect(true).toBe(false)
} catch (error) {
  expect(error).toBeDefined()
}
```

Another way to avoid this is using a jest matcher that makes certain that an error is thrown such as [`toThrowErrorMatchingSnapshot`]('https://jestjs.io/docs/en/expect#tothrowerrormatchingsnapshot) (although this doesn't work with async functions)

**Comment by lmars** [comment]
Has this now been addressed?

**Comment by MrTibbles** [comment]
I believe so yes
