### ISSUE TITLE
Application ID should no longer be validated as an ethereum address

### ISSUE THREAD

**Issue by malimccalla** [jaakmusic/jaak.js#58]
**Describe the bug**
The API has recently changed its handling of applications so that ids are now uuids instead of ethereum addresses. We need to update the validation of `applicationId` in the contructor of the `JAAK` class to avoid the following error

```error
TypeError: Expected 96ec1093-a78f-42b3-8b5f-8f818857c43e to be a valid Ethereum address
    at isValidAddress
```

**To Reproduce**
1. Instantiate the JAAK class with the `applicationId` key being a uuid

**Expected behavior**
I expect to be able to create a jaak instance and no errors to be thrown.

**Package name and version**
playback

**Comment by lmars** [comment]
In general, let's just make sure that values like this that come from the API are non-empty strings and not worry about whether they are UUIDs / Ethereum addresses /  elephants / whatever.

**Comment by malimccalla** [comment]
### 🐘

**Comment by lmars** [comment]
`applicationID: "🐘🐘🐘"`
