### ISSUE TITLE
playback-utils: Add toJWK method to Key class

### ISSUE THREAD

**Issue by MrTibbles** [jaakmusic/jaak.js#73]
**What package is your feature proposal for?**
`@jaak/playback-utils`

**Is your feature request related to a problem?**
When device keys are being registered the public key needs to exported in `jwk` format, calling the `exportKey` method on from the SubtleCrypto API, to then be sent to the Playback API `registerDevice` mutation.

**Describe the solution you'd like**
To simplify this interaction a method should be added to the `Key` class which returns the public key in JWK format:
```js
class Key {
  ...
  toJWK() {
    return Jose.crypto.subtle.exportKey('jwk', this.publicKey)
  }
}
```

**Comment by malimccalla** [comment]
As discussed in slack, the desired API is

```js
const key = await Key.generate(true)
const jwk = await key.toJWK({ private: true })
```
